const text = [
  "I'm baby seitan thundercats fam kale chips fanny pack. Whatever chia vinyl, succulents green juice austin drinking vinegar art party locavore pok pok snackwave adaptogen 3 wolf moon. Taiyaki jianbing subway tile bushwick street art keffiyeh. Vinyl 3 wolf moon affogato hashtag disrupt, viral coloring book subway tile brooklyn. Wayfarers vinyl authentic celiac irony pok pok activated charcoal selvage shoreditch umami craft beer yr fashion axe.",
  "Succulents paleo next level brooklyn 90's cliche waistcoat master cleanse brunch cloud bread retro freegan chambray. Copper mug brooklyn bespoke, fingerstache hella praxis ramps wolf small batch twee. Cliche crucifix 8-bit portland, bespoke af air plant vice. Banh mi neutra hashtag selvage, blog jean shorts lomo ramps marfa cardigan. Tilde copper mug live-edge, wayfarers direct trade retro vice succulents la croix kale chips unicorn air plant palo santo semiotics. DSA twee cliche, four loko kickstarter roof party ennui cornhole irony tumblr. Four loko pop-up yes plz ennui synth.",
  "Ethical blue bottle knausgaard gluten-free. XOXO mustache kale chips bespoke put a bird on it ramps try-hard hoodie vexillologist. You probably haven't heard of them meh leggings truffaut forage shoreditch. Try-hard truffaut put a bird on it adaptogen.",
  "Activated charcoal tbh brooklyn craft beer, twee kale chips 3 wolf moon succulents subway tile literally vexillologist cronut offal fanny pack mumblecore. La croix praxis forage letterpress ethical fashion axe neutra authentic stumptown. Praxis occupy plaid skateboard. Direct trade roof party air plant beard church-key fixie irony vaporware mlkshk kogi aesthetic man bun gentrify plaid gochujang.",
  "Quinoa DSA activated charcoal humblebrag, intelligentsia lumbersexual tattooed pickled direct trade. Hell of direct trade vegan palo santo 8-bit whatever. Literally austin tousled swag, humblebrag heirloom put a bird on it trust fund pickled banh mi celiac. Ethical venmo actually, small batch knausgaard authentic stumptown mlkshk microdosing. Keytar mixtape photo booth brunch. Ramps tote bag kinfolk VHS narwhal mustache biodiesel ugh kitsch. Meh bushwick health goth prism biodiesel jianbing slow-carb occupy, green juice four loko man bun keffiyeh trust fund offal fixie.",
  "Crucifix asymmetrical gastropub, cloud bread kogi af occupy farm-to-table retro praxis raclette intelligentsia blog irony. Seitan iPhone tumblr, fanny pack brunch art party shabby chic XOXO cliche air plant sartorial raclette prism hella next level. Lumbersexual enamel pin brooklyn, wolf echo park jean shorts raw denim chia art party asymmetrical truffaut PBR&B church-key. Franzen microdosing artisan migas tumeric.",
  "Flexitarian pabst edison bulb messenger bag meggings mumblecore 3 wolf moon gluten-free tilde. Sustainable 3 wolf moon mixtape, readymade health goth 90's chambray vegan sriracha. Pork belly snackwave try-hard kinfolk lomo iceland shoreditch asymmetrical pok pok godard bicycle rights everyday carry migas. Gochujang banh mi palo santo helvetica, jianbing shaman mustache before they sold out. Edison bulb intelligentsia waistcoat selfies freegan marfa austin heirloom fam vape.",
  "Vaporware green juice heirloom, prism cliche narwhal schlitz XOXO af cornhole beard. Chia shabby chic 8-bit pop-up bitters woke cronut tacos enamel pin knausgaard activated charcoal kinfolk deep v. Franzen chartreuse gastropub vaporware try-hard drinking vinegar celiac farm-to-table edison bulb 90's. Copper mug meh readymade hexagon umami.",
];
export default text;
